# Generated by Django 2.2.6 on 2020-11-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_newpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
